FROM python:3.11

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --upgrade pip "poetry==1.4.2"
RUN pip install --upgrade pip "gunicorn==20.1.0"
RUN poetry config virtualenvs.create false --local
COPY pyproject.toml ./
RUN poetry install

COPY mysite .

CMD ["gunicorn", "mysite.wsgi:application", "--bind", "0.0.0.0:8000"]