
FROM python:3.11-slim


RUN apt-get update && apt-get install -y \
    curl \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*


RUN curl -sSL https://install.python-poetry.org | python3 -


ENV PATH="${PATH}:/root/.local/bin"


WORKDIR /app


COPY pyproject.toml poetry.lock* ./


RUN --mount=type=ssh poetry install --no-root


COPY app/ ./app/


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]